import { Inter } from 'next/font/google'
import { ReactNode } from 'react'

import './globals.css'
import { SessionProvider } from '~/providers/NextAuthSessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Social Media Belt',
    template: 'Social Media Belt | %s',
  },
  description: 'Generated by create next app',
}

interface IRootLayoutProps {
  children: ReactNode
  session: any
}

export default function RootLayout({ children, session }: IRootLayoutProps) {
  return (
    <html data-mode="dark" lang="pt-BR" className={inter.className}>
      <body>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  )
}
